### ISSUE TITLE
Issues Joining a Server With Agenta on Both

### ISSUE THREAD

**Issue by wolflord212312** [Hanro50/Agenta#1]
CrashLog
[crash-2024-06-24_03.58.06-client.txt](https://github.com/user-attachments/files/15952430/crash-2024-06-24_03.58.06-client.txt)
[Full Client log](https://mclo.gs/L2e07ly)
Tested Both Java 7 and Java 8 On client Server is on Java 7
Server is running Cauldron-MCPC-Plus-1.6.4-1.965.01.205

[Server log ](https://mclo.gs/56NhycN)

**Comment by wolflord212312** [comment]
Am using Agenta-1.7.jar

**Comment by wolflord212312** [comment]
Also tried the Version released before Agenta-1.7.jar But same Crash

**Comment by wolflord212312** [comment]
agent-1.7.jar
backpack-1.28.37-1.6.x.jar
BackTools2.0.1.zip
BiblioCraft[v1.5.5].zip
CodeChickenCore-1.6.4-0.9.0.9-universal.jar
CraftPresence-2.4.2+1.6.4.jar.disabled
Decocraft_1.10.0_1.6.4.zip
DynamicLights_1.6.4.zip
Evoc_1.0.0a.jar
flatsigns-1.6.2-universal-1.4.0.15.jar
Hats2.1.8.zip
HatStand2.1.0.zip
iChunUtil2.4.0.zip
JourneyMap4.0.3_Unlimited_MC1.6.4.jar
Log4jPatcher-1.0.1.jar
MobDismemberment2.0.0.zip
MobiusCore_1.2.2_1.6.4.jar
MorePlayerModels_1.6.2-1.6.4.zip
Morpheus-1.6.4-1.2.32.jar
neiaddons-mc164-1.10.5.70.jar
NotEnoughItems-1.6.4-1.6.1.9-universal.jar
NotEnoughPets-1.6.4-2.3.6.jar
Opis_1.2.2.zip
OptiFine_1.6.4_HD_U_C8.jar
serializationisbad-1.5.2.jar
ShadersModCore-v2.2.3-mc1.6.4-f965.jar
traincraft-4.2.1_011.jar
VeinMiner.0.12.3_MC1.6.jar
VillageInfo_Forge_1.6.4_2.0-b3.zip
WailaHarvestability-mc1.6.4-1.1.0.jar
1.6.4
PartyMod-Beta-V1.2
_1.6.4__Mouse_Tweaks_2.3.4.zip

**Comment by Hanro50** [comment]
Version 1.8 should fix this. Thanks for the report!
