### ISSUE TITLE
Sound problems with Reforged (b1.7.3): "Access is denied" 

### ISSUE THREAD

**Issue by Thrillville109** [Hanro50/Agenta#2]
When attempting to proxy then add sounds with Reforged installed (instead of Regular Forge 1.0.6), I get this error:

[Agenta:log] Proxying resource [newsound/mob/creeper1.ogg]
java.io.FileNotFoundException: D:\Users\thril\PrismLauncher\instances\Modded Beta 1.7.3\.minecraft\resources\newsound\mob\creeper1.ogg (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at cz.a(SourceFile:105)
	at cz.a(SourceFile:93)
	at cz.run(SourceFile:42)
	
If there was a way to add a config to disable the sound proxy or to have this issue fixed that would be great.

**Comment by Hanro50** [comment]
I can add a config option to knock out the sound proxy. It'll likely be agenta.resources.proxy with the same syntax we use to knock out the skin resizer code. 

We don't have a good way to do config files without touching minecraft more directly. Future versions may attempt to add support if we figure out a way to do it consistently.

**Comment by Hanro50** [comment]
You can now turn off audio routing in 1.8.5 by setting agenta.assets.routing to false in agenta's config file.
